### ISSUE TITLE
Don't force spec.wait to true on kustomization

### ISSUE THREAD

**Issue by isugimpy** [flux-subsystem-argo/fsa#14]
spec.wait being forcefully true is causing problems with using Argo Rollouts with flamingo.  Would it be possible to expose this as a field and not force it in the template?

**Comment by chanwit** [comment]
hi @isugimpy 
could you elaborate more about the bug? 

are you using the UI to create Flux resources with auto-create flag?

**Comment by isugimpy** [comment]
Apologies, I could have been considerably more detailed.

Argo Rollouts presents status in an odd way which causes incompatibility with Flux (I have open issues and a PR to help with this right now on Flux).  By forcing `spec.wait` to be true in generated Kustomizations off of an Application, a state gets entered where a given Application can never succeed at a deploy due to the Kustomization failing the health check for these resources.  This is true of some other types of resources which contain nonstandard status that Flux doesn't understand as well, with a notable one being at least one of the custom resources for Istio.  Being able to toggle off `spec.wait` allows the user the choice to bypass the health checking at the top level Kustomization and rely on the UI to know if a deploy was successful.

Taking this logic a step further, exposing many of the spec fields for Kustomizations would be extremely valuable.  Most are omitted, and the template being hardcoded means the only workaround at scale is to fork this project.  Otherwise, users are forced to deploy the Kustomizations and their underlying sources to destination workload clusters, largely defeating the value proposition of Flamingo.

**Comment by chanwit** [comment]
I went thru the ArgoCD application spec, and couldn't find a good place to expose the underlying Flux KS template.

Where would be the most convenient place for you to specifying those fields?

I am assuming that you'd like to it via UI too?

**Comment by isugimpy** [comment]
UI would be pretty helpful.  As a means to an end, annotations would work.  There could be individual field mappings where the value is just a string containing JSON.  Alternatively, maybe as list items under `spec.syncOptions`?

**Comment by chanwit** [comment]
```yaml
apiVersion: v1
kind: Application
metadata:
  name: app-1
  annotations:
    flamingo/kustomize-override: |
      spec:
        wait: false
```

would this work for you?

**Comment by isugimpy** [comment]
That would be fantastic, yeah!

**Comment by chanwit** [comment]
implemented in f37869ecfa33c08e2be637c096c2e4884d7246a4

**Comment by chanwit** [comment]
Here's the new image: `ghcr.io/flux-subsystem-argo/fsa/argocd:v2.9.6-fl.23-main-f37869ec`

Let me know if it's solved your problem.

**Comment by isugimpy** [comment]
This looks incredibly promising.  I'll give it a shot right now!

**Comment by isugimpy** [comment]
This does appear to be working in *almost* all ways.  The only problem I've got now is that the generated Kustomization can't have fields removed from it, so once you set them the one time, they're there forever.  That's a pretty uncommon case, I think, so I'm not terribly worried about it.  If there's a way to toggle to do a replace rather than an apply on the generated Kustomization, that would likely solve this, but I didn't see a way offhand.

**Comment by chanwit** [comment]
That would be the behaviour of the flux-subsystem flag.
once the underlying Flux objects are created, they will not be overwritten.

I should have added "flamingo/generated=true" as the indicator to allow object re-generation.

**Comment by chanwit** [comment]
follow-up #15

**Comment by isugimpy** [comment]
Fantastic.  Thank you so much.  I'll close this issue out!
